name: Release (macOS .dmg)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: macos-${{ hashFiles('**/Cargo.lock','**/Cargo.toml') }}-bundle

      - name: Install just
        run: cargo install just --locked || true

      # Your Just recipe installs cargo-bundle if missing and calls hdiutil
      - name: Build .app and .dmg
        run: just dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stitch-dmg
          path: dist/*.dmg

      - name: Attach to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.dmg
